name: Print Software Versions

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  print_node_version:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Print Node.js version
        run: |
          echo "Node.js Version:"
          node --version

  print_postgresql_version:
    runs-on: ubuntu-latest
    steps:
      - name: Print PostgreSQL version
        run: |
          echo "PostgreSQL Version:"
          psql --version
