name: Print Software Versions

on:
  push:
    branches:
      - main
jobs:
  print_node_version:
    runs-on: ubuntu-latest
    steps:
      - name: Print Node.js version
        run: |
          echo "Node.js Version:"
          node --version
  print_postgresql_version:
    runs-on: ubuntu-latest
    steps:
      - name: Print PostgreSQL version
        run: |
          echo "PostgreSQL Version:"
          psql --version
